version: '3.5'
services: 
   web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
        - "3000:3000"
    volumes: 
        - /app/usr/node_modules
        - .:/app/usr
    environment: 
        - CHOKIDAR_USEPOLLING=true  
   tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
        - /app/usr/node_modules
        - .:/app/usr     
    command: ["npm" , "run" , "test"]    